version: "3"
services:
  moviemasher:
    build:
      dockerfile: ./Dockerfile.cnf
      context: ../../
    image: moviemasher/moviemasher.js:5.0.0
    container_name: moviemasher
    entrypoint: npm
    command: start --port=${PORT:-8570}
    ports:
      - "${PORT:-8570}:${PORT:-8570}"
    volumes:
      - ../..:/home/node/app
      - ../../temporary:/temporary
