version: "3"
services:
  moviemasher:
    build:
      dockerfile: ./Dockerfile.cnf
      context: ../../
    image: moviemasher/moviemasher.js:5.0.2
    container_name: moviemasher
    ports:
      - "8570:8570"
      - "8571:8571"
    volumes:
      - ./server-config.json:/home/node/app/workspaces/example-express-react/dist/server-config.json
      # - ../../temporary:/home/node/app/temporary
      # - ../../docs/:/home/node/app/docs/
      # - ../../dev/:/home/node/app/dev/
      # - ../../packages/:/home/node/app/packages/
      # - ../../workspaces/:/home/node/app/workspaces/
